version: '3.4'

services:
  shopping-store-api:
    image: shoppingstoreapi
    container_name: Shopping-Store-API
    ports:
      - "5000:80"
      - "6333:443"
    build:
      context: .
      dockerfile: Shopping-Store-API\Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql-server-2019
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=sa&123456
